Resources:
  notesTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "${self:custom.notesDDB}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TimeToLiveSpecification: 
        AttributeName: ttl
        Enabled: true
